try{
    console.log(a)
}
catch(err)
{
    console.log(err)
    console.log("error in pgm")
}
finally{
    console.log("end of pgm")
}
console.log("hello from other part")